export enum ProjectsConst {
    FETCH_ALL_PROJECTS = 'FETCH_ALL_PROJECTS',
    CREATE_PROJECT = 'CREATE_PROJECT',
    GET_DETAILS_PROJECT = 'GET_DETAILS_PROJECT',
    EDIT_PROJECT = 'EDIT_PROJECT',
    ADD_TASK_TO_PROJECT = 'ADD_TASK_TO_PROJECT',
    GET_PROJECTS_FOR_LOGGED_USER = 'GET_PROJECTS_FOR_LOGGED_USER',
}
